# Generated by Django 5.2.5 on 2025-08-12 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cooking_time',
            new_name='cooking_time_in_minutes',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredients',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='instructions',
        ),
    ]
