# Generated by Django 5.2.5 on 2025-08-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_cooking_time_recipe_cooking_time_in_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cooking_time_in_minutes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='event_time',
            field=models.TimeField(blank=True, help_text='Hora em que o evento ocorreu (formato HH:MM)', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='location',
            field=models.CharField(blank=True, help_text='Onde o evento ocorreu', max_length=255, null=True),
        ),
    ]
