# Generated by Django 5.2.5 on 2025-08-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipe_cooking_time_in_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagem do evento', null=True, upload_to='recipes/images/'),
        ),
    ]
